---
- hosts: masters
  remote_user: root
  strategy: free

  tasks:
    - name: copy the deployer spec
      template: src=flex_deployer_pod.yaml dest=/root/flex_deployer_pod.yaml

    - name: login as system
      shell: oc login -u system:admin

    - name: add cluster role to developer user
      shell: oc adm policy add-cluster-role-to-user cluster-admin developer

    - name: create the flex deployer pod
      shell: oc create -f /root/flex_deployer_pod.yaml

    - name: verify that the flex driver pod is running
      shell: oc get pods -l name=ovirt-flexvolume-driver -o json | jq '.items[] | select (.status.phase == "Running")' -e
      register: result
      until: result.rc ==  0
      retries: 60
      delay: 1

    - name: verify that the volume provisioner pod is running
      shell: oc get pods -l name=ovirt-volume-provisioner -o json | jq '.items[] | select (.status.phase == "Running")' -e
      register: result
      until: result.rc ==  0
      retries: 60
      delay: 1

    - name: deploy a test pod that uses flex
      shell: oc create -f https://raw.githubusercontent.com/oVirt/ovirt-openshift-extensions/master/deployment/example/test-pod-with-flex.yaml

    - name: wait fot the test pod with flex to run
      shell: oc get pods -l name=testpodwithflex -o json | jq '.items[] | select (.status.phase == "Running")' -e
      register: result
      until: result.rc == 0
      retries: 60
      delay: 1

    - name: verify the test pod sees the flex mounted file system
      shell: oc exec -it testpodwithflex ls -la /var

    - name: shutdown the testpodwithflex container
      shell: oc delete pods/testpodwithflex

    - name: wait for the pod to be down
      shell: oc get pods -l name=testpodwithflex -o json | jq '.items[] | select (.status.phase == "Down")' -e
      register: result
      until: result.rc == 0
      retries: 60
      delay: 1

    - name: verify ovirt disks are detached - using oc events
      shell: oc get events -l TODO EXTRACT EVENT
      register: result
      until: result.rc == 0
      retries: 60
      delay: 1
