apiVersion: v1
kind: Pod
metadata:
  name: flex-deployer
spec:
  containers:                            
  - env:
    - name: ENGINE_IP
      value: "{{ engine_ip }}"
    - name: ENGINE_URL
      value: "{{ engine_url }}" 
    - name: ENGINE_USER
      value: "{{ engine_user }}"
    - name: ENGINE_PASS
      value: "{{ engine_password }}"
    - name: ADMIN_USER
      value: "developer"
    - name: ADMIN_PASS
      value: "developer"
    image: docker.io/rgolangh/ovirt-flexvolume-driver-apb
    args: ["provision", "-e", "admin_user=$(ADMIN_USER)", "-e", "admin_password=$(ADMIN_PASS)","-e", "cluster=openshift","-e", "namespace=default","-e", "engine_password=$(ENGINE_PASS)","-e", "engine_url=$(ENGINE_URL)","-e", "engine_username=$(ENGINE_USER)"]
    imagePullPolicy: Never
    name: ovirt-flexvolume-deployer
    restartPolicy: Never
    hostAliases:
    - ip: "{{ engine_ip }}"
      hostnames:
      - "engine"
    securityContext:
      allowPriviligedEscalation: true
    volumeMount:
      - mountPath: /opt/apb/.kube
        name: kube-home
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccount: default               
  volumes:                              
  - name: kube-home
    hostPath:
      path: /root/.kube/
