---
apiVersion: batch/v1
kind: Job
metadata:
  name: flex-deployer
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - env:
            - name: ENGINE_URL
              value: "{{ engine_url }}"
            - name: ENGINE_USER
              value: "{{ engine_user }}"
            - name: ENGINE_PASS
              value: "{{ engine_password }}"
            - name: ADMIN_USER
              value: "developer"
            - name: ADMIN_PASS
              value: "developer"
          image: quay.io/rgolangh/ovirt-flexvolume-driver-apb
          args:
            - provision
            - "-e"
            - '{"admin_user":"$(ADMIN_USER)", "admin_password":"$(ADMIN_PASS)", "cluster":"openshift", "namespace":"default", "engine_password":"$(ENGINE_PASS)", "engine_url":"$(ENGINE_URL)", "engine_username":"$(ENGINE_USER)"}'
          imagePullPolicy: Always
          name: ovirt-flexvolume-deployer
          restartPolicy: Never
          securityContext:
            allowPriviligedEscalation: true
          volumeMount:
            - mountPath: /opt/apb/.kube
              name: kube-home
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      volumes:
        - name: kube-home
          hostPath:
            path: /root/.kube/
