[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bytefmt"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/kubernetes-incubator/external-storage"
  version = "v4.0.0"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.3"

# solves https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true
