---
- hosts: k8s-ovirt-nodes:k8s-ovirt-masters
  remote_user: root
  vars:
    # defaults - override in an inventory file or include
    engine_url: https://hostname/ovirt-engine/api
    engine_username: admin@internal
    engine_password: pass
    engine_insecure: false
    engine_ca_file:
    vendor: ovirt
    driver: ovirt-flexdriver
    plugin_dir: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/{{ vendor }}~{{ driver }}"
  tasks:

    - name: Create the plugin directory
      file:
        path: "{{ plugin_dir }}"
        state: directory

    - name: Copy oVirt flexvolume driver config
      template:
        src: ovirt-flexdriver.conf.j2
        dest: "{{ plugin_dir }}/{{ driver }}.conf"
        force: yes

    - name: Copy oVirt flexvolume driver binary
      copy:
        src: ovirt-flexdriver
        dest: "{{ plugin_dir }}/.{{ driver }}"
        mode: a+x
        force: yes

    - name: Atomic move of the file to the real name to avoid plugin init problems
      command: mv {{ plugin_dir}}/.{{ driver }} {{ plugin_dir}}/{{ driver }}
