kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ovirt
provisioner: ovirt-volume-provisioner
parameters:
  # oVirt target storage domain name for the created disks.
  ovirtStorageDomain: "nfs"
  # Specify thin provisioning or not (default true)
  # The provisioner will figure out the disk type for you
  ovirtDiskThinProvisioning: true
  # The file system to create on the disk prior to attaching it to the container.
  # If the filesystem already exists, don't re-recreate.
  fsType: ext4
