kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ovirt
provisioner: external/ovirt 
parameters:
  type: io1
  iopsPerGB: "10"
  ovirtStorageDomain: "nfs"
  # specifing a disk format is a must and depends on
  # the type of the domain - block-storage(iscsi/FC) or file(NFS/gluster...)
  ovirtDiskFormat: "cow"
  fsType: ext4


