---
# These are the expected vars, override them in the inventory
# or pass in extra args when invoking the playbook
# engine_url: https://hostname/ovirt-engine/api
# engine_username: admin@internal
# engine_password: pass
# engine_insecure: false
# engine_ca_file:
- hosts: k8s-ovirt-masters
  remote_user: root
  vars:
    manifest_file: ovirt-provisioner-manifest.yaml
    deprovision: false
    provisioner_version: {{ lookup('env','OVIRT_PROVISIONER_VERSION') }}
  tags: tagged
  tasks:
    - name: Copy the all-in-one manifest
      template:
        src: "{{ manifest_file }}.j2"
        dest: /root/{{ manifest_file }}
        force: yes

    - name: Provision the provisioner and its companion object
      command: kubectl create -f /root/{{ manifest_file }}
      when: not deprovision

    - name: De-Provision the provisioner and its companion object
      command: kubectl delete -f /root/{{ manifest_file }}
      when: deprovision
