- name: 'DOCKER_BUILDER_API_KEY' 
  valueFrom:
    secretKeyRef:
        name: 'docker_api_key'
        key: 'key'

- name: QUAY_API_KEY
  valueFrom:
    secretKeyRef:
      name: 'QUAY_API_KEY'
      key: 'quai_api_key'

